version: '2'
services:
  test_module-app:
    image: test_module
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://test_module-postgresql:5432/test_module
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://test_module-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://test_module-elasticsearch:9200
    ports:
      - 8080:8080
  test_module-postgresql:
    extends:
      file: postgresql.yml
      service: test_module-postgresql
  test_module-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: test_module-elasticsearch
